// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU_hItn29s6X45fGLV-JVCOhhihsQKMGk',
    appId: '1:802676514185:web:222354e696d17f50595558',
    messagingSenderId: '802676514185',
    projectId: 'flutterproto-40c6e',
    authDomain: 'flutterproto-40c6e.firebaseapp.com',
    storageBucket: 'flutterproto-40c6e.firebasestorage.app',
    measurementId: 'G-5EJVZLB1N9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyjnSZ1o4ltzbxrrO1_OQmYwR0Fkaecys',
    appId: '1:802676514185:ios:672eaa4f1183e7dd595558',
    messagingSenderId: '802676514185',
    projectId: 'flutterproto-40c6e',
    storageBucket: 'flutterproto-40c6e.firebasestorage.app',
    iosBundleId: 'com.example.proto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU_hItn29s6X45fGLV-JVCOhhihsQKMGk',
    appId: '1:802676514185:web:7ac91ed8f415b70a595558',
    messagingSenderId: '802676514185',
    projectId: 'flutterproto-40c6e',
    authDomain: 'flutterproto-40c6e.firebaseapp.com',
    storageBucket: 'flutterproto-40c6e.firebasestorage.app',
    measurementId: 'G-VVBQFJR7E8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyjnSZ1o4ltzbxrrO1_OQmYwR0Fkaecys',
    appId: '1:802676514185:ios:672eaa4f1183e7dd595558',
    messagingSenderId: '802676514185',
    projectId: 'flutterproto-40c6e',
    storageBucket: 'flutterproto-40c6e.firebasestorage.app',
    iosBundleId: 'com.example.proto',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFhpoRN3RnxObcR3j5xFil9T1FEfUSqB8',
    appId: '1:802676514185:android:129705f50e6ecb1f595558',
    messagingSenderId: '802676514185',
    projectId: 'flutterproto-40c6e',
    storageBucket: 'flutterproto-40c6e.firebasestorage.app',
  );

}